drop table IF EXISTS users, categories, locations, comments, events, requests, compilations, events_compilations;
create TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(250) NOT NULL,
                                     email VARCHAR(254) NOT NULL,
                                     CONSTRAINT PK_USER PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);
create TABLE IF NOT EXISTS categories (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(50) NOT NULL,
                                     CONSTRAINT PK_CATEGORY PRIMARY KEY (id),
                                     CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);
create TABLE IF NOT EXISTS locations (
                                    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                    lat REAL NOT NULL,
                                    lon REAL NOT NULL,
                                    CONSTRAINT PK_LOCATION PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS events (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     annotation VARCHAR(2000) NOT NULL,
                                     category_id BIGINT NOT NULL,
                                     description VARCHAR(7000) NOT NULL,
                                     event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     location_id BIGINT NOT NULL,
                                     paid BOOLEAN NOT NULL,--TRUE, FALSE
                                     participant_limit INT,
                                     request_moderation BOOLEAN,--TRUE, FALSE
                                     title VARCHAR(120) NOT NULL,
                                     state VARCHAR(9), --PENDING, CANCELED, PUBLISHED
                                     created TIMESTAMP WITHOUT TIME ZONE,
                                     initiator_id BIGINT NOT NULL,
                                     published_on TIMESTAMP WITHOUT TIME ZONE,

                                     CONSTRAINT PK_EVENT PRIMARY KEY (id),
                                     CONSTRAINT FK_CATEGORY_ID FOREIGN KEY(category_id) REFERENCES categories(id) ON delete CASCADE,
                                     CONSTRAINT FK_INITIATOR_ID FOREIGN KEY(initiator_id) REFERENCES users(id) ON delete CASCADE,
                                     CONSTRAINT FK_LOCATION_ID FOREIGN KEY(location_id) REFERENCES locations(id) ON delete CASCADE
);
create TABLE IF NOT EXISTS requests (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     created TIMESTAMP WITHOUT TIME ZONE,
                                     event_id BIGINT NOT NULL,
                                     requester_id BIGINT NOT NULL,
                                     status VARCHAR(9), --PENDING, CANCELED, PUBLISHED

                                     CONSTRAINT PK_REQUEST PRIMARY KEY (id),
                                     CONSTRAINT FK_EVENT_ID FOREIGN KEY(event_id) REFERENCES events(id) ON delete CASCADE,
                                     CONSTRAINT FK_REQUESTER_ID FOREIGN KEY(requester_id) REFERENCES users(id) ON delete CASCADE
);
create TABLE IF NOT EXISTS compilations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     pinned BOOLEAN, --TRUE, FALSE
                                     title VARCHAR(50),

                                     CONSTRAINT PK_COMPILATION PRIMARY KEY (id)
);
create TABLE IF NOT EXISTS events_compilations (
                                    compilation_id BIGINT REFERENCES compilations (id),
                                    event_id       BIGINT REFERENCES events (id),
                                    CONSTRAINT PK_EVENT_COMPILATION  PRIMARY KEY (compilation_id, event_id)
);
create TABLE IF NOT EXISTS comments (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     created TIMESTAMP WITHOUT TIME ZONE,
                                     text VARCHAR(2000) NOT NULL,
                                     author_id BIGINT NOT NULL,
                                     event_id BIGINT NOT NULL,

                                     CONSTRAINT PK_COMMENT_ID PRIMARY KEY (id),
                                     CONSTRAINT FK_EVENT_ID_COMMENT FOREIGN KEY(event_id) REFERENCES events(id) ON delete CASCADE,
                                     CONSTRAINT FK_AUTHOR_ID FOREIGN KEY(author_id) REFERENCES users(id) ON delete CASCADE
);
