CREATE TABLE IF NOT EXISTS endpointhit (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     app VARCHAR(255) NOT NULL,
                                     uri VARCHAR(255) NOT NULL,
                                     ip VARCHAR(15) NOT NULL,
                                     created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                     CONSTRAINT PK_ENDPOINTHIT PRIMARY KEY (id)
);