version: '3.1'
services:
  stats-server:
    build: ./statistic-service/statistic-server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5433/statistic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  stats-db:
    image: postgres:14-alpine
    container_name: statistic-db
    ports:
      - "6543:5433"
    environment:
      - POSTGRES_DB=statistic
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: ./main-service
    image: main-service-image
    container_name: main-service-container
    ports:
      - "8080:8080"